import openai from '../services/openAiService.js';
import buildRecipePrompt from '../utils/buildRecipePrompt.js';
import recipeConfig from '../../config/recipeConfig.js';

/**
 * Handles incoming requests and generates a response using OpenAI's GPT-3 language model.
 * Provides recipe recommendations based on a list of ingredients provided in the request body.
 *
 * @param {Object} req - The incoming request object.
 * @param {Object} res - The outgoing response object.
 * @returns {Object} - JSON response containing the recipe recommendation generated by the OpenAI language model.
 */
export default async function recipeController(req, res) {
  const { ingredients } = req.body;
  const prompt = buildRecipePrompt(ingredients, recipeConfig);
  const completion = await openai.createChatCompletion({
    model: 'gpt-3.5-turbo',
    messages: [
      {
        role: 'system',
        content:
          'You are a professional chef who recommends recipes based on ingredients',
      },
      {
        role: 'user',
        content: prompt,
      },
    ],
    temperature: 0.7,
    max_tokens: 1000,
    stream: false,
  });

  res.json({ content: completion.data.choices[0].message.content });
}
